### ISSUE TITLE
Apply-PnPTenantTemplate, The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by JimmyHang** [pnp/PnP-Sites-Core#2648]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I'm trying Apply-PnPTenantTemplate to provisiong a following guides from the last PnPSIG call

#### Observed Behavior
I can authenticate with SharePoint Online with my Global Admin Account, the account don't have MFA because it's a dev environment. I'm getting (403) Forbidden, I've verified that PnP Power App exist in Azure, and have right delegated permissions.

`PS C:\Development\PnPTemplates> Connect-PnPOnline "https://tenant.sharepoint.com/" -UseWebLogin
PS C:\Development\PnPTemplates> Apply-PnPTenantTemplate -Path .\demo-team-template.xml -Parameters @{"TeamTitle"="PnPTeamDemoSIG01A";"TeamAlias"="pnpteamdemosig01a"} -Verbose
powershell.exe Error: 0 : 2020-05-18 23:40:59.1228      [OfficeDevPnP.Core]     [0]     [Error] ExecuteQuery threw following exception: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext().  0ms
Apply-PnPTenantTemplate : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Apply-PnPTenantTemplate -Path .\demo-team-template.xml -Parameters @{ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Apply-PnPTenantTemplate], WebException
    + FullyQualifiedErrorId : System.Net.WebException,SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate`

![image](https://user-images.githubusercontent.com/18226765/82263391-14eb5300-9963-11ea-87d3-7f26ee5c88c4.png)

I've must have missed some permissions somewhere but can't figure out what?

#### Steps to Reproduce

Try to run "Apply-PnPTenantTemplate"

Thank you

**Comment by JimmyHang** [comment]
Closing this issue, as I repeated this process today and it's working as expected.. ;)
