### ISSUE TITLE
OfficeDevPnp.core

### ISSUE THREAD

**Issue by Abhilashh-Reddi** [pnp/PnP-Sites-Core#2676]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ X] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 16.0.4966.1000

#### Expected or Desired Behavior
Successful authentication to Sharepoint 2016 On premise from CRM 365.

#### Observed Behavior
We have a custom plugin for Dynamics CRM 2016 on premise which connects to Sharepoint 2016 on premise using OfficeDevPNP Core dll.

We have migrated to dynamics CRM 365 version 9 from Dynamics CRM 2016, and the custom plugin stopped working. We tried with various versions of the OfficeDevPNP Core but it is pointing to same error as mentioned below:
We tried to add different versions of OfficeDEVPnP Core dll still the same error pops out.

The Web Service plug-in failed in OrganizationId: d34ea34c-9eeb-dd11-a84e-00215ad1c350; SdkMessageProcessingStepId: e799e2a9-75bd-e811-815b-0050568d3c97; EntityName: opportunity; Stage: 40; MessageName: Update; AssemblyName: Henley.WF.plugin.UpdateNumberOfDependants, Henley.WF, Version=1.0.0.2, Culture=neutral, PublicKeyToken=265dfc72f5fd8a78; ClassName: Henley.WF.plugin.UpdateNumberOfDependants; Exception: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Henley.WF.plugin.UpdateNumberOfDependants.updateNODSP(IOrganizationService service, Entity entity, IPluginExecutionContext context, Int32 finalcount)
   at Henley.WF.plugin.UpdateNumberOfDependants.Execute(IServiceProvider serviceProvider) in C:\Users\abhilash.reddy\Documents\Visual Studio Code\With DEVPNPCORE - D365\Crm2011DistributeWF\CrmHenleyWorkFlow\plugin\UpdateNumberOfDependants.cs:line 83
   at Microsoft.Crm.Extensibility.V5PluginProxyStep.ExecuteInternal(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)

#### Steps to Reproduce
We use the below code 
OfficeDevPnP.Core.AuthenticationManager am = new OfficeDevPnP.Core.AuthenticationManager();
            ClientContext clientContext = am.GetADFSUserNameMixedAuthenticatedContext(siteURL, userName, pwd, domain, token, adfsRealm);

It is working for Dynamics CRM 2016 but not for Dynamics 365

**Comment by Abhilashh-Reddi** [comment]
Hello Team, 

Could you please help us on this issue. Please let us know if you need any more information.

Kind Regards
Abhilash.
